allowBuilds:
  ejs: false
  esbuild: true
  puppeteer: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@puppeteer/browsers'
  - puppeteer-core
  - puppeteer
  - miniflare@4.20260616.0
  - wrangler@4.101.0
